name: coverage
on:
  push:
    branches:
      - main
    tags:
      - '!*' # Do not execute on tags
    # paths:
    #   - '*.go'
  pull_request:
    paths:
      - '!*.MD'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: actions/checkout@v3
    - run: ./test_cover.sh

  coverage:
    needs: [ test ]
    name: Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: go test ./... -coverprofile=c.out
        coverageLocations: ${{github.workspace}}/c.out:gocov
        prefix: github.com/arszen123/gpool